# Site
title: Esprit de paix
description: "Carnet d'étude / Guérison spirituelle"
url: 
logo: index.svg                                     # Site logo
locale: fr_FR

# Left Block Images
background:
  homepage:                           # this image will be shown on homepage's left block
  post-list: images/unsplash-image-10.jpg             # this image will be shown on post list page
  default-post: images/unsplash-gallery-image-3.jpg   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
#google-analytics: UA-XXXXX-Y

# Social Links
email: 'c.d&#101;lm&#97;%736&#55;&#64;g&#109;a%69&#108;%2e&#99;o%6d'
#google.plus:        username
#twitter:            username
facebook:           christian.delmas.54
#github:             username
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link


# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
